### PR TITLE
Downgrade TargetFrameworkVersion to v4.5

### PR DESCRIPTION
**Pull request by Kahbazi**
Adding support for .net framework v4.5

### CODE REVIEW

**Comment by stackia** [comment]
Thanks!

**Comment by Kahbazi** [comment]
You're welcome. 
When can you push the nuget package?

**Comment by stackia** [comment]
Because the package name "SimpleInjector" causes confusion with SimpleInjector's official extensions, I was asked to remove this from nuget. And I don't think there is still anybody using this package (it's only used in one of my projects), so I was not going to change the package name.

**Comment by Kahbazi** [comment]
well I am using this package and using .net framework v4.5, and I appreciate it, if I can access it via nuget.

**Pull request merged**
